---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: products
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products
        image: cmyazurecontainerregistry.azurecr.io/productsbackend:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: products